### ISSUE TITLE
Hacer guía de cómo contribuir

### ISSUE THREAD

**Issue by Charly6596** [ConsejoInfUMA/Aya#8]
Esta guía se usará para futuros proyectos, debe incluir todo el proceso desde hacer un fork hasta un pull request, pasando por cómo clonar el repositorio
como referencia: 
https://github.com/susam/gitpr
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/
https://github.com/joelparkerhenderson/github_special_files_and_paths#contributing

**Comment by restebanlm** [comment]
Hola @Charly6596 ! Lo necesitas en español?

**Comment by Charly6596** [comment]
> Hola @Charly6596 ! Lo necesitas en español?

Hola buenas, sí @restebanlm

**Comment by restebanlm** [comment]
Bien. Me pongo en ello.
