### ISSUE TITLE
Traducir documentación al inglés

### ISSUE THREAD

**Issue by Charly6596** [ConsejoInfUMA/Aya#9]
- Crear un archivo README-ES.md y mover el README.md actual
- La traducción debe ir en el README.md
- Ambos archivos deben estar referenciados entre sí, es decir, habrá un enlace para ir al otro archivo

Referencia:
https://guides.github.com/features/mastering-markdown/

**Comment by restebanlm** [comment]
Hola @Charly6596 ! Tomo la tarea.
